<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Bulk SEO Actions — friendly admin page.
 *
 * Each action card explains, in plain language:
 *   - What it does (visible result).
 *   - Where the change appears (post body / HTML <meta> / JSON-LD / DB index).
 *   - Why it improves SEO.
 *   - Recommended use cases.
 *   - Filters that make sense for that specific action.
 *
 * The "features" array drives the per-action filter inputs in the modal
 * (assets/seo.js → buildFiltersBlock). Add a new feature flag here to
 * surface its input automatically.
 */
function botwriter_seo_page_bulk_actions() {
    $image_settings_url = admin_url('admin.php?page=botwriter_settings#main-tab-imagesettings');

    $actions = array(
        // --- Snippets / meta -------------------------------------------------
        'regen_meta_description' => array(
            'label' => __('Refresh meta descriptions', 'botwriter'),
            'icon'  => 'edit',
            'tagline' => __('Rewrite the snippet shown under your link in Google.', 'botwriter'),
            'what'  => __('Generates a new 150–158 character meta description with AI, using your post content.', 'botwriter'),
            'where' => __('In the page <meta name="description"> tag — the snippet Google shows under your title in search results. Not visible inside the post.', 'botwriter'),
            'why'   => __('A relevant, keyword-rich snippet can lift click-through rate by 20–40% even without ranking changes. Empty or generic descriptions are auto-generated by Google and rarely match search intent.', 'botwriter'),
            'badges' => array('search', 'meta', 'ai'),
            'use_cases' => array(
                __('Posts imported without meta descriptions.', 'botwriter'),
                __('Old posts whose description is just the first sentence of the article.', 'botwriter'),
            ),
            'features' => array('missing_meta', 'score', 'only_changed'),
            'undo' => 'meta',
            'destructive' => false,
        ),
        'refresh_intro' => array(
            'label' => __('Strengthen intro & keyword placement', 'botwriter'),
            'icon'  => 'editor-paragraph',
            'tagline' => __('Rewrite the opening so the article starts stronger and places the focus keyword early.', 'botwriter'),
            'what'  => __('Rewrites the first 1-3 paragraphs with AI. It keeps the rest of the article intact and, if needed, can also suggest/save a missing primary keyword first.', 'botwriter'),
            'where' => __('Visible at the top of the post body (post_content). Readers see it immediately and the first paragraph becomes more aligned with what searchers expect.', 'botwriter'),
            'why'   => __('The intro is where Google and users validate intent fast. A weak opening often fails the “primary keyword in first paragraph” check and loses engagement before readers scroll.', 'botwriter'),
            'badges' => array('content', 'ai'),
            'use_cases' => array(
                __('Articles whose first paragraph is too generic or buries the topic.', 'botwriter'),
                __('Posts missing a primary keyword in SEO meta and in the opening.', 'botwriter'),
            ),
            'features' => array('intro_paragraphs', 'auto_keyword', 'score', 'only_changed'),
            'args' => array('intro_paragraphs' => 2, 'auto_keyword' => 1),
            'undo' => 'content',
            'destructive' => false,
        ),
        'expand_content' => array(
            'label' => __('Expand thin content', 'botwriter'),
            'icon'  => 'editor-expand',
            'tagline' => __('Append a new supporting section when the article is too short for the topic.', 'botwriter'),
            'what'  => __('Generates one extra section with an H2 and supporting paragraphs, then appends it to the article to push thin posts above your chosen word-count target.', 'botwriter'),
            'where' => __('Visible inside the post body, usually near the end of the article. It extends the page with more context, examples or clarifications.', 'botwriter'),
            'why'   => __('Very short posts struggle to cover intent depth, long-tail queries and semantic variants. Adding one useful section is often enough to recover the “word count” check without rewriting the whole article.', 'botwriter'),
            'badges' => array('content', 'ai'),
            'use_cases' => array(
                __('Legacy posts under 300-500 words that answer the topic too briefly.', 'botwriter'),
                __('Pages that rank but need more topical depth before doing title/meta refreshes.', 'botwriter'),
            ),
            'features' => array('target_words', 'score', 'only_changed'),
            'args' => array('target_words' => 450),
            'undo' => 'content',
            'destructive' => false,
        ),
        'regen_seo_title' => array(
            'label' => __('Refresh SEO titles', 'botwriter'),
            'icon'  => 'editor-textcolor',
            'tagline' => __('Rewrite only the SEO title — your post title stays untouched.', 'botwriter'),
            'what'  => __('Generates a new 50–60 character SEO title and saves it through your active SEO plugin (Yoast, Rank Math, AIOSEO) or BotWriter\'s native meta. Your visible post title is NOT changed.', 'botwriter'),
            'where' => __('In the browser tab and as the headline shown in Google search results. Replaces the auto-generated <title> tag.', 'botwriter'),
            'why'   => __('The SEO title is the most important on-page CTR signal. Front-loaded keywords + an emotional or numeric hook can dramatically improve clicks vs. ranking position.', 'botwriter'),
            'badges' => array('search', 'meta', 'ai'),
            'use_cases' => array(
                __('Posts with no custom SEO title (Google falls back to your H1).', 'botwriter'),
                __('Posts whose H1 is too long and gets truncated by Google.', 'botwriter'),
            ),
            'features' => array('missing_seo_title', 'score', 'only_changed'),
            'undo' => 'meta',
            'destructive' => false,
        ),

        // --- Media ----------------------------------------------------------
        'regen_alt_text' => array(
            'label' => __('Fill missing image ALT', 'botwriter'),
            'icon'  => 'format-image',
            'tagline' => __('Describe images so Google and screen readers understand them.', 'botwriter'),
            'what'  => __('Scans the post HTML for <img> tags without ALT text and fills them with concise, language-aware descriptions generated by AI.', 'botwriter'),
            'where' => __('Inside the post HTML (img alt="…"). Visible to screen readers, indexed by Google Image Search, and read by accessibility audits.', 'botwriter'),
            'why'   => __('ALT text is a primary ranking signal for Google Images and a WCAG accessibility requirement. Missing ALTs lose image-search traffic and trigger compliance warnings.', 'botwriter'),
            'badges' => array('content', 'a11y', 'ai'),
            'use_cases' => array(
                __('Old posts written before image SEO was a priority.', 'botwriter'),
                __('Posts imported via RSS or migration tools that strip ALTs.', 'botwriter'),
            ),
            'features' => array('only_changed', 'score'),
            'undo' => 'media',
            'destructive' => false,
        ),
        'normalize_headings' => array(
            'label' => __('Normalize heading levels', 'botwriter'),
            'icon'  => 'editor-ol',
            'tagline' => __('Clean body headings so H1 stays unique and subheadings become easier to scan.', 'botwriter'),
            'what'  => __('Normalizes the heading structure already inside the article: it can demote in-content H1 tags to H2 and, when the post only uses H2s, create one H3 level without rewriting the full copy.', 'botwriter'),
            'where' => __('Visible inside the post body. Readers notice cleaner section hierarchy and the analysis stops flagging H1 misuse.', 'botwriter'),
            'why'   => __('A single H1 per page is still the safest structure. Cleaner H2/H3 hierarchy improves scanability, accessibility, and helps the SEO analysis reflect a more editorial structure.', 'botwriter'),
            'badges' => array('content'),
            'use_cases' => array(
                __('Imported posts that accidentally include another H1 inside the content.', 'botwriter'),
                __('Articles with flat headings where every section is at the same level.', 'botwriter'),
            ),
            'features' => array('demote_h1', 'add_subheadings', 'score', 'only_changed'),
            'args' => array('demote_h1' => 1, 'add_subheadings' => 1),
            'undo' => 'content',
            'destructive' => false,
        ),

        // --- Linking --------------------------------------------------------
        'rebuild_internal_links' => array(
            'label' => __('Rebuild internal links', 'botwriter'),
            'icon'  => 'admin-links',
            'tagline' => __('Insert contextual links that pass authority between your posts.', 'botwriter'),
            'what'  => __('Re-runs the BotWriter internal-link engine. Inserts up to N contextual <a> tags pointing to semantically related posts on your site.', 'botwriter'),
            'where' => __('Visible inline inside the post body (post_content). Also tracked in BotWriter\'s links table for audit.', 'botwriter'),
            'why'   => __('Internal links spread PageRank, help Google discover deep pages, and increase session depth. Orphan pages (no incoming links) and dead-end pages (no outgoing links) consistently underperform.', 'botwriter'),
            'badges' => array('content', 'autopilot'),
            'use_cases' => array(
                __('Orphan pages — no other post links to them.', 'botwriter'),
                __('Dead-end pages — they don\'t link out to any other post.', 'botwriter'),
                __('After publishing several new posts in a topic cluster.', 'botwriter'),
            ),
            'features' => array('link_role', 'score', 'only_changed'),
            'undo' => 'content',
            'destructive' => false,
        ),
        'add_external_references' => array(
            'label' => __('Add external references', 'botwriter'),
            'icon'  => 'external',
            'tagline' => __('Append a “Further reading” block with authoritative external sources.', 'botwriter'),
            'what'  => __('Uses the configured SERP provider to fetch top external results for the post topic, excludes your own domain, and appends a short reference list at the end of the article.', 'botwriter'),
            'where' => __('Visible at the bottom of the post body as a references block with clickable external links.', 'botwriter'),
            'why'   => __('Some articles look self-contained but cite nothing outside your site. Adding 1-3 strong references helps the analysis pass the external-links check and gives readers trustworthy follow-up sources.', 'botwriter'),
            'badges' => array('content'),
            'use_cases' => array(
                __('Guides and explainers that currently have zero outbound references.', 'botwriter'),
                __('Posts where you want a low-risk external citation block without editing the whole article by hand.', 'botwriter'),
            ),
            'features' => array('external_links_count', 'score', 'only_changed'),
            'args' => array('external_links_count' => 2),
            'undo' => 'content',
            'destructive' => false,
        ),

        // --- Enrichment -----------------------------------------------------
        'regen_faq' => array(
            'label' => __('Generate FAQ blocks', 'botwriter'),
            'icon'  => 'format-chat',
            'tagline' => __('Add an FAQ section + FAQPage schema for rich results.', 'botwriter'),
            'what'  => __('Generates 4–6 question / answer pairs from your post content and stores them in post meta (_botwriter_seo_faq).', 'botwriter'),
            'where' => __('TWO places: (1) appended at the bottom of the post — visible to readers; (2) injected as FAQPage JSON-LD in the page <head> — read by Google for rich results.', 'botwriter'),
            'why'   => __('FAQ schema is one of the few rich-result types still widely shown by Google. Eligible pages can take dramatically more SERP real estate, which boosts CTR and time-on-page.', 'botwriter'),
            'badges' => array('content', 'schema', 'ai'),
            'use_cases' => array(
                __('Long-form articles, how-to guides, product pages.', 'botwriter'),
                __('Posts that already rank but get low CTR.', 'botwriter'),
            ),
            'features' => array('missing_faq', 'faq_visibility', 'score', 'only_changed'),
            'undo' => 'meta',
            'destructive' => false,
        ),

        // --- URLs (advanced) ------------------------------------------------
        'rewrite_slug' => array(
            'label' => __('Rewrite slug for SEO', 'botwriter'),
            'icon'  => 'admin-site-alt3',
            'tagline' => __('Shorten and clean up URLs (auto-creates 301 redirects).', 'botwriter'),
            'what'  => __('Generates a short, keyword-focused slug for the post and renames the URL. The original URL automatically gets a 301 redirect to the new one — inbound links keep working.', 'botwriter'),
            'where' => __('In the public URL (and therefore in browser history, social shares, etc.). Old URL is preserved as a redirect entry in BotWriter\'s redirects table.', 'botwriter'),
            'why'   => __('Short, keyword-rich URLs are easier to share, rank slightly better, and look more trustworthy in SERP. But changing URLs is destructive: external links and shares to the OLD URL keep working only thanks to the auto-redirect.', 'botwriter'),
            'badges' => array('url', 'destructive', 'redirect', 'ai'),
            'use_cases' => array(
                __('Posts with very long auto-generated slugs (typical from imported titles).', 'botwriter'),
                __('Posts whose slug doesn\'t contain the focus keyword.', 'botwriter'),
            ),
            'features' => array('slug_length_gt', 'confirm_destructive'),
            'undo' => 'none',
            'destructive' => true,
        ),

        // --- Semantic -------------------------------------------------------
        'optimize_images' => array(
            'label' => __('Optimize images (WebP / compress)', 'botwriter'),
            'icon'  => 'images-alt2',
            'tagline' => __('Convert and compress your images so Google sees them as fast-loading.', 'botwriter'),
            'what'  => sprintf(
                /* translators: 1: target format, 2: max width, 3: max KB */
                __('Re-encodes the featured image and inline images of each post to %1$s, resizes wider than %2$dpx, and compresses below %3$dKB. Uses your global Image Post-Processing settings.', 'botwriter'),
                strtoupper((string) get_option('botwriter_image_output_format', 'webp')),
                (int) get_option('botwriter_image_max_width', 1200),
                (int) get_option('botwriter_image_max_filesize', 120)
            ),
            'what_html'  => sprintf(
                /* translators: 1: target format, 2: max width, 3: max KB, 4: settings URL */
                __('Re-encodes the featured image and inline images of each post to %1$s, resizes wider than %2$dpx, and compresses below %3$dKB. Uses your <a href="%4$s">global Image Post-Processing settings</a>.', 'botwriter'),
                strtoupper((string) get_option('botwriter_image_output_format', 'webp')),
                (int) get_option('botwriter_image_max_width', 1200),
                (int) get_option('botwriter_image_max_filesize', 120),
                esc_url($image_settings_url)
            ),
            'where' => __('Updates the actual image files in your Media Library and rewrites the URLs inside post_content when the file extension changes.', 'botwriter'),
            'why'   => __('Image weight is the #1 PageSpeed/Core Web Vitals offender. Serving WebP under 120KB lets Google show your pages in Discover and improves LCP on mobile.', 'botwriter'),
            'badges' => array('content', 'index'),
            'use_cases' => array(
                __('Older posts uploaded as JPEG/PNG before WebP support.', 'botwriter'),
                __('Imported sites with oversized hero images (>500KB).', 'botwriter'),
            ),
            'features' => array('only_changed'),
            'undo' => 'none',
            'destructive' => false,
        ),
        'embed_index' => array(
            'label' => __('Rebuild semantic index', 'botwriter'),
            'icon'  => 'networking',
            'tagline' => __('Refresh the vector index used by smart linking & search.', 'botwriter'),
            'what'  => __('Computes (or refreshes) embeddings for matching posts and stores them in BotWriter\'s embeddings table.', 'botwriter'),
            'where' => __('Hidden — stored in the database. Powers internal-link suggestions, cannibalization detection, semantic search and topic clustering. Not visible to readers or Google.', 'botwriter'),
            'why'   => __('Most BotWriter SEO features (smart links, cannibalization, related-post detection) only work for posts that have a current embedding. Re-index after big content updates or when adding many new posts at once.', 'botwriter'),
            'badges' => array('index', 'autopilot'),
            'use_cases' => array(
                __('First-time setup or after a content migration.', 'botwriter'),
                __('After enabling a new SEO module that depends on semantic similarity.', 'botwriter'),
            ),
            'features' => array('only_changed'),
            'undo' => 'none',
            'destructive' => false,
        ),
    );

    // Single shared job feed (one job runs at a time on the actions slot).
    $state   = botwriter_seo_job_state('actions');
    $pct     = $state['total'] > 0 ? round(($state['done'] / $state['total']) * 100) : 0;
    $running = in_array($state['status'], array('running', 'pending'), true);
    $progress_title_default = __('Bulk action progress', 'botwriter');
    $progress_title = !empty($state['action_label']) ? (string) $state['action_label'] : $progress_title_default;

    // ----- Intro hero -------------------------------------------------------
    echo '<div class="bw-card bw-bulk-hero">';
    echo '<div class="bw-bulk-hero-icon"><span class="dashicons dashicons-superhero"></span></div>';
    echo '<div class="bw-bulk-hero-body">';
    echo '<h2>' . esc_html__('Bulk SEO actions', 'botwriter') . '</h2>';
    echo '<p>' . esc_html__('Apply one SEO improvement at a time across many posts in the background. Pick an action, choose how many posts to target with the filters, and BotWriter does the rest. Runs are throttled and resumable, so you can safely close this page.', 'botwriter') . '</p>';
    echo '<div class="bw-cost-note" tabindex="0">';
    echo '<span class="dashicons dashicons-info-outline" aria-hidden="true"></span>';
    echo '<span class="bw-cost-note-copy">' . esc_html__('Typical cost with budget models: optimizing 100 posts of about 600 words usually stays around $0.02-$0.15 for Title + Meta + Intro + FAQ + Slug.', 'botwriter') . '</span>';
    echo '<span class="bw-cost-note-tip">';
    echo '<strong>' . esc_html__('How this estimate was calculated', 'botwriter') . '</strong>';
    echo '<span>' . esc_html__('Based on the real prompts used by Bulk Actions and current public pricing for the cheapest supported models.', 'botwriter') . '</span>';
    echo '<span>' . esc_html__('Examples for 100 posts: Groq Llama 3.1 8B about $0.02, Gemini 2.5 Flash Lite about $0.06, GPT-4o mini about $0.09, GPT-5.4 nano about $0.15.', 'botwriter') . '</span>';
    echo '<span>' . esc_html__('FAQ and AI internal links are the main cost drivers. If AI internal links are enabled, add roughly another $0.01-$0.08 per 100 posts. GPT-5.4 mini is closer to about $0.54.', 'botwriter') . '</span>';
    echo '<span>' . esc_html__('External references and embedding refresh are not part of this estimate because they do not use the same LLM flow.', 'botwriter') . '</span>';
    echo '</span>';
    echo '</div>';
    echo '</div>';
    echo '</div>';

    // ----- Live progress card ----------------------------------------------
    echo '<div id="bw-live-progress-card" class="bw-card bw-live-progress-card" tabindex="-1"><h3><span class="dashicons dashicons-controls-play"></span> <span class="bw-live-progress-title" data-default-title="' . esc_attr($progress_title_default) . '">' . esc_html($progress_title) . '</span></h3>';
    echo '<div class="bw-job" data-job="actions">';
    echo '<div class="bw-job-label">' . esc_html(ucfirst($state['status'])) . '</div>';
    echo '<div class="bw-progress"><div data-progress="' . esc_attr((string) $pct) . '"></div></div>';
    echo '<div class="stats"><span class="bw-job-stats">' . (int) $state['done'] . ' / ' . (int) $state['total'] . ' (' . esc_html((string) $pct) . '%)</span><span class="bw-job-message">' . esc_html($state['message'] ?? '') . '</span></div>';
    echo '<div class="bw-job-feed-wrap"' . ($running ? '' : ' hidden') . '>';
    echo '<div class="bw-job-feed-title"><span class="dashicons dashicons-list-view"></span> ' . esc_html__('Live results', 'botwriter') . '</div>';
    echo '<ul class="bw-job-feed" id="bw-job-feed-actions"></ul>';
    echo '</div>';
    echo '<div class="bw-card-actions">';
    echo '<button type="button" class="bw-button danger bw-job-cancel" data-job="actions"' . ($running ? '' : ' disabled') . '>';
    echo '<span class="dashicons dashicons-no-alt"></span> ' . esc_html__('Cancel current run', 'botwriter');
    echo '</button>';
    echo '</div>';
    echo '</div>';
    echo '</div>';

    botwriter_seo_render_bulk_undo_history_section();

    // Render cards only (2-by-2), collapsed by default.
    $order = array(
        'regen_meta_description',
        'refresh_intro',
        'expand_content',
        'regen_seo_title',
        'regen_alt_text',
        'normalize_headings',
        'rebuild_internal_links',
        'add_external_references',
        'regen_faq',
        'rewrite_slug',
        'embed_index',
        'optimize_images',
    );

    echo '<div class="bw-seo-grid cols-2 bw-action-grid">';
    foreach ($order as $action_key) {
        if (!isset($actions[$action_key])) { continue; }
        botwriter_seo_render_action_card($action_key, $actions[$action_key], $running);
    }
    // Future-proof: render any extra action not listed in $order.
    foreach ($actions as $action_key => $meta) {
        if (in_array($action_key, $order, true)) { continue; }
        botwriter_seo_render_action_card($action_key, $meta, $running);
    }
    echo '</div>';
}

/**
 * Render a single bulk-action card with what / where / why / use-cases /
 * badges and the Configure & Run button.
 */
function botwriter_seo_render_action_card($action_key, $meta, $running) {
    $badge_labels = array(
        'search'     => array(__('Affects search snippet', 'botwriter'), 'bw-chip-info'),
        'meta'       => array(__('HTML <meta> only', 'botwriter'), 'bw-chip-muted'),
        'content'    => array(__('Visible in post', 'botwriter'), 'bw-chip-success'),
        'a11y'       => array(__('Accessibility', 'botwriter'), 'bw-chip-info'),
        'schema'     => array(__('Adds JSON-LD schema', 'botwriter'), 'bw-chip-info'),
        'index'      => array(__('Hidden DB index', 'botwriter'), 'bw-chip-muted'),
        'autopilot'  => array(__('Compatible with Autopilot', 'botwriter'), 'bw-chip-success'),
        'ai'         => array(__('Uses AI quota', 'botwriter'), 'bw-chip-warn'),
        'url'        => array(__('Changes URL', 'botwriter'), 'bw-chip-warn'),
        'redirect'   => array(__('Auto 301 redirect', 'botwriter'), 'bw-chip-info'),
        'destructive'=> array(__('Destructive — confirm required', 'botwriter'), 'bw-chip-danger'),
    );
    $undo_labels = array(
        'meta'    => array(
            __('Simple UNDO: yes', 'botwriter'),
            'bw-chip-success',
            __('Can restore the previous SEO/meta value with a simple before-run snapshot.', 'botwriter')
        ),
        'content' => array(
            __('Simple UNDO: yes', 'botwriter'),
            'bw-chip-success',
            __('Can restore the previous post body with one content snapshot taken before the action runs.', 'botwriter')
        ),
        'media'   => array(
            __('Simple UNDO: yes', 'botwriter'),
            'bw-chip-info',
            __('Can restore the previous ALT values with a lightweight media/meta snapshot.', 'botwriter')
        ),
        'none'    => array(
            __('Simple UNDO: no', 'botwriter'),
            'bw-chip-danger',
            __('This action should stay outside the simple UNDO flow because reverting it cleanly is risky or low-value.', 'botwriter')
        ),
    );
    $undo_key = isset($meta['undo']) && isset($undo_labels[$meta['undo']]) ? $meta['undo'] : 'none';
    list($undo_label, $undo_class, $undo_help) = $undo_labels[$undo_key];

    echo '<div class="bw-card bw-action-card' . ($meta['destructive'] ? ' is-destructive' : '') . '">';
    echo '<details class="bw-action-details">';

    // Compact header (collapsed state).
    echo '<summary class="bw-action-summary">';
    echo '<div class="bw-action-head">';
    echo '<span class="bw-action-icon"><span class="dashicons dashicons-' . esc_attr($meta['icon']) . '"></span></span>';
    echo '<div class="bw-action-titles">';
    echo '<div class="bw-action-title-row">';
    echo '<h4>' . esc_html($meta['label']) . '</h4>';
    echo '<span class="bw-info-chip bw-action-undo-chip ' . esc_attr($undo_class) . '">' . esc_html($undo_label) . '</span>';
    echo '</div>';
    echo '<p class="bw-action-tagline">' . esc_html($meta['tagline']) . '</p>';
    echo '</div>';
    echo '</div>';
    echo '<span class="bw-action-toggle dashicons dashicons-arrow-down-alt2" aria-hidden="true"></span>';
    echo '</summary>';

    // Expanded body.
    echo '<div class="bw-action-body">';

    if (!empty($meta['badges'])) {
        echo '<div class="bw-action-chips">';
        foreach ($meta['badges'] as $b) {
            if (!isset($badge_labels[$b])) { continue; }
            list($label, $class) = $badge_labels[$b];
            echo '<span class="bw-info-chip ' . esc_attr($class) . '">' . esc_html($label) . '</span>';
        }
        echo '</div>';
    }

    echo '<dl class="bw-action-explain">';
    echo '<dt><span class="dashicons dashicons-admin-tools"></span> ' . esc_html__('What it does', 'botwriter') . '</dt>';
    echo '<dd>' . (!empty($meta['what_html']) ? wp_kses_post($meta['what_html']) : esc_html($meta['what'])) . '</dd>';
    echo '<dt><span class="dashicons dashicons-visibility"></span> ' . esc_html__('Where the result appears', 'botwriter') . '</dt>';
    echo '<dd>' . esc_html($meta['where']) . '</dd>';
    echo '<dt><span class="dashicons dashicons-chart-line"></span> ' . esc_html__('Why it improves SEO', 'botwriter') . '</dt>';
    echo '<dd>' . esc_html($meta['why']) . '</dd>';
    echo '<dt><span class="dashicons dashicons-undo"></span> ' . esc_html__('Undo status', 'botwriter') . '</dt>';
    echo '<dd>' . esc_html($undo_help) . '</dd>';
    echo '</dl>';

    if (!empty($meta['use_cases'])) {
        echo '<div class="bw-action-uses">';
        echo '<strong>' . esc_html__('Best for', 'botwriter') . ':</strong>';
        echo '<ul>';
        foreach ($meta['use_cases'] as $u) {
            echo '<li>' . esc_html($u) . '</li>';
        }
        echo '</ul>';
        echo '</div>';
    }

    echo '<div class="bw-card-actions">';
    echo '<button type="button" class="bw-button primary bw-job-configure"';
    echo ' data-job="actions"';
    echo ' data-mode="action"';
    echo ' data-action-label="' . esc_attr($meta['label']) . '"';
    echo ' data-destructive="' . ($meta['destructive'] ? '1' : '0') . '"';
    echo ' data-features=\'' . esc_attr(wp_json_encode($meta['features'])) . '\'';
    echo ' data-args=\'' . esc_attr(wp_json_encode(array_merge(array('action' => $action_key), isset($meta['args']) && is_array($meta['args']) ? $meta['args'] : array()))) . '\'';
    echo ($running ? ' disabled' : '');
    echo '>';
    echo '<span class="dashicons dashicons-admin-tools"></span> ' . esc_html__('Configure & Run', 'botwriter');
    echo '</button>';
    echo '</div>';

    echo '</div>'; // .bw-action-body
    echo '</details>';
    echo '</div>';
}
